spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://uat:5432/cloud-user
    username: postgres
    password: admin
    type: com.zaxxer.hikari.HikariDataSource